# Generated by Django 5.2.4 on 2025-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='non_category',
            field=models.CharField(blank=True, help_text='请输入作品涉及的非遗类别（如：漆器、蜡染、傩戏等）', max_length=50, verbose_name='非遗类别'),
        ),
    ]
