# Generated by Django 5.2.4 on 2025-07-26 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_video_non_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'voted_at'], name='list_vote_user_id_78fa42_idx'),
        ),
    ]
