# Generated by Django 5.2.4 on 2025-08-03 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_vote_list_vote_user_id_78fa42_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('video', '视频'), ('image', '图片'), ('qrcode', '二维码')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media_assets/%Y/%m/')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'video', 'voted_at'], name='list_vote_user_id_b089a2_idx'),
        ),
    ]
